var languages = {              /* (optional) define **ADDITIONAL** custom languages */
	'italian' : {
		'country': 'Italy',
		'language' : 'Italian',
		'countryTranslated': 'Italia',
		'languageTranslated': 'Italiano',
		'flag' : {
			'url' : 'http://upload.wikimedia.org/wikipedia/commons/f/fb/Farm-Fresh_italy.png', /* url of flag image */
			'class' : 'italian-flag' /* (optional) class to assign to the flag (e.g., for css styling) */
		}
	},
	'turkian' : {
		'country': 'Turkey',
		'language' : 'Turkish',
		'countryTranslated': 'Türkiye',
		'languageTranslated': 'Türkçe',
	},
	'indian' : {
		'country': 'India',
		'language' : 'Hindi',
		'countryTranslated': 'भारत',
		'languageTranslated': 'हिन्द',
	},
	'brazilian' : {
		'country': 'Brazil',
		'language' : 'Portuguese',
		'countryTranslated': 'Brasil',
		'languageTranslated': 'Português',
	},
	'french' : {
		'country': 'France',
		'language' : 'French',
		'countryTranslated': 'France',
		'languageTranslated': 'Français',
	},
	'german' : {
		'country': 'Germany',
		'language' : 'German',
		'countryTranslated': 'Deutschland',
		'languageTranslated': 'Deutsch',
	},
	
};



var translation_string = {
	/* 
	 * You can specify the text string to translate directly... 
	 */
	'We Are Doing Great,' : {
		'italian' : 'Stiamo andando alla grande,',
		'jp_JP' : '私たちは素晴らしいことをしている、',
		'ar_TN' : 'نحن نفعل العظمى ،',
		'tr_TR' : 'Harika Yapıyoruz,',
		'de_DE' : 'Wir machen das großartig,',
		'hi_IN' : 'हम बहुत अच्छा कर रहे हैं,',
		'pt_BR' : 'estamos indo muito bem,',
		'fr_FR' : 'nous allons très bien,',
	},
	'Almost Done...' : {
		'italian' : 'Quasi fatto...',
		'jp_JP' : 'ほぼ完了しました...',
		'ar_TN' : 'يكاد ينتهي...',
		'tr_TR' : 'Neredeyse bitti...',
		'de_DE' : 'Fast fertig...',
		'hi_IN' : 'लगभग हो गया...',
		'pt_BR' : 'Quase pronto...',
		'fr_FR' : 'Presque fini...',
	},
	'Days' : {
		'italian' : 'giorni',
		'jp_JP' : '日々',
		'ar_TN' : 'أيام',
		'tr_TR' : 'günler',
		'de_DE' : 'Tage',
		'hi_IN' : 'दिन',
		'pt_BR' : 'Dias',
		'fr_FR' : 'Journées',
	},
	'Hours' : {
		'italian' : 'Ore',
		'jp_JP' : '時間',
		'ar_TN' : 'ساعات',
		'tr_TR' : 'Saatler',
		'de_DE' : 'Std',
		'hi_IN' : 'घंटे',
		'pt_BR' : 'Horas',
		'fr_FR' : 'Heures',
	},
	'Minutes' : {
		'italian' : 'Minuti',
		'jp_JP' : '議事録',
		'ar_TN' : 'الدقائق',
		'tr_TR' : 'Dakika',
		'de_DE' : 'Protokoll',
		'hi_IN' : 'मिनट',
		'pt_BR' : 'Minutos',
		'fr_FR' : 'Minutes',
	},
	'Second' : {
		'italian' : 'Seconda',
		'jp_JP' : '第二',
		'ar_TN' : 'ثانيا',
		'tr_TR' : 'İkinci',
		'de_DE' : 'Zweite',
		'hi_IN' : 'पल',
		'pt_BR' : 'Segunda',
		'fr_FR' : 'Seconde',
	},
	'Get In Touch' : {
		'italian' : 'Mettiti in contatto',
		'jp_JP' : '連絡する',
		'ar_TN' : 'ابقى على تواصل',
		'tr_TR' : 'Temasta olmak',
		'de_DE' : 'In Kontakt kommen',
		'hi_IN' : 'संपर्क में रहो',
		'pt_BR' : 'Entrar em contato',
		'fr_FR' : 'Entrer en contact',
	},
	'Subscribe Now' : {
		'italian' : 'Iscriviti ora',
		'jp_JP' : '今すぐ購読する',
		'ar_TN' : 'إشترك الآن',
		'tr_TR' : 'Şimdi abone olun',
		'de_DE' : 'Abonniere jetzt',
		'hi_IN' : 'अभी ग्राहक बनें',
		'pt_BR' : 'Inscreva-se agora',
		'fr_FR' : 'Abonnez-vous maintenant',
	},
	'Full Name' : {
		'italian' : 'Nome e cognome',
		'jp_JP' : 'フルネーム',
		'ar_TN' : 'الاسم الكامل',
		'tr_TR' : 'Ad Soyad',
		'de_DE' : 'Vollständiger Name',
		'hi_IN' : 'पूरा नाम',
		'pt_BR' : 'Nome completo',
		'fr_FR' : 'Nom complet',
	},
	'Your Email Address' : {
		'italian' : 'Il tuo indirizzo di posta elettronica',
		'jp_JP' : 'メールアドレス',
		'ar_TN' : 'عنوان بريدك الإلكتروني',
		'tr_TR' : 'e',
		'de_DE' : 'deine Emailadresse',
		'hi_IN' : 'आपका ईमेल पता',
		'pt_BR' : 'Seu endereço de email',
		'fr_FR' : 'Votre adresse email',
	},
	'Your Message' : {
		'italian' : 'Il tuo messaggio',
		'jp_JP' : 'あなたのメッセージ',
		'ar_TN' : 'رسالتك',
		'tr_TR' : 'Mesajın',
		'de_DE' : 'Deine Nachricht',
		'hi_IN' : 'आपका सन्देश',
		'pt_BR' : 'Sua mensagem',
		'fr_FR' : 'Votre message',
	},
	'Send Message' : {
		'italian' : 'Invia messaggio',
		'jp_JP' : 'メッセージを送る',
		'ar_TN' : 'إرسال رسالة',
		'tr_TR' : 'Mesaj gönder',
		'de_DE' : 'Nachricht senden',
		'hi_IN' : 'मेसेज भेजें',
		'pt_BR' : 'Enviar mensagem',
		'fr_FR' : 'Envoyer le message',
	},
	'Contact Us' : {
		'italian' : 'Contattaci',
		'jp_JP' : 'お問い合わせ',
		'ar_TN' : 'اتصل بنا',
		'tr_TR' : 'Bize Ulaşın',
		'de_DE' : 'Kontaktiere uns',
		'hi_IN' : 'संपर्क करें',
		'pt_BR' : 'Contate-Nos',
		'fr_FR' : 'Nous contacter',
	},
	'View Map' : {
		'italian' : 'Guarda la mappa',
		'jp_JP' : '地図を見ます',
		'ar_TN' : 'إعرض الخريطة',
		'tr_TR' : 'Haritayı incele',
		'de_DE' : 'Ansichts Karte',
		'hi_IN' : 'मानचित्र',
		'pt_BR' : 'Ver mapa',
		'fr_FR' : 'Voir la carte',
	},
	'Close' : {
		'italian' : 'Vicina',
		'jp_JP' : '閉じる',
		'ar_TN' : 'قريب',
		'tr_TR' : 'Kapat',
		'de_DE' : 'Schließen',
		'hi_IN' : 'बंद करे',
		'pt_BR' : 'Fechar',
		'fr_FR' : 'Fermer',
	},
	'Location' : {
		'italian' : 'Posizione',
		'jp_JP' : 'ロケーション',
		'ar_TN' : 'موقعك',
		'tr_TR' : 'yer',
		'de_DE' : 'Ort',
		'hi_IN' : 'स्थान',
		'pt_BR' : 'Localização',
		'fr_FR' : 'Emplacement',
	},
	'Email' : {
		'italian' : 'E-mail',
		'jp_JP' : 'Eメール',
		'ar_TN' : 'البريد الإلكتروني',
		'tr_TR' : 'E-posta',
		'de_DE' : 'Email',
		'hi_IN' : 'ईमेल',
		'pt_BR' : 'O email',
		'fr_FR' : 'Email',
	},
	'Subscribe Newsletter' : {
		'italian' : 'Iscriviti alla newsletter',
		'jp_JP' : 'ニュースレターを購読する',
		'ar_TN' : 'اشترك في النشرة الإخبارية',
		'tr_TR' : 'Bültene Abone Ol',
		'de_DE' : 'Abonniere den Newsletter',
		'hi_IN' : 'न्यूज़लेटर प्राप्त करें',
		'pt_BR' : 'Assine o Newsletter',
		'fr_FR' : 'Abonnez-vous à la newsletter',
	},
	'Lorem ipsum dolor sit amet consectetur adipisicing elit sed eiusmod tempor incididunt labore dolore.' : {
		'italian' : 'Lorem ipsum dolor sit amet consectetur adipisicing elit sed eiusmod time incididunt labore dolore.',
		'jp_JP' : 'Lorem ipsum dolor sit amet consectetur adipisicing elit sed eiusmod tempor incididunt Labore dolore。',
		'ar_TN' : 'Lorem ipsum dolor sit amet consectetur adipisicing elit sed eiusmod tempor incididunt labore dolore.',
		'tr_TR' : 'Lorem ipsum dolor oturmak amet consectetur adipisicing elit sed eiusmod tempor incididunt labore dolore.',
		'de_DE' : 'Lorem ipsum dolor sit amet consectetur adipisicing elit sed eiusmod tempor incididunt labore dolore.',
		'hi_IN' : 'लोरम इप्सम डोलर अमेट कंसेटेटुरिप एडिटिसिलेटिंग इलीट सेड इय्समोड अस्थायी इन्सीडिडंट लेबोर डोलोर बैठते हैं।.',
		'pt_BR' : 'Lorem ipsum dolor senta-se em um consectetur adipisicing elit sed eiusmod tempor incididunt labore dolore.',
		'fr_FR' : 'Lorem ipsum dolor assis amet consectetur adipisicing elit sed eiusmod tempor incididunt labore dolore.',
	},
	'© 2020 - Made with' : {
		'italian' : '© 2020 - Realizzato con',
		'jp_JP' : '©2020-で作られた',
		'ar_TN' : '© 2020 - صنع مع',
		'tr_TR' : '© 2020 - ile üretilmiştir',
		'de_DE' : '© 2020 - Gemacht mit',
		'hi_IN' : '© 2020 - के साथ बनाया गया',
		'pt_BR' : '© 2020 - Feito com',
		'fr_FR' : '© 2020 - Fabriqué avec',
	},
	'Check Demo' : {
		'italian' : 'Controlla la demo',
		'jp_JP' : 'デモを確認する',
		'ar_TN' : 'تحقق التجريبي',
		'tr_TR' : 'Demoyu Kontrol Et',
		'de_DE' : 'Demo überprüfen',
		'hi_IN' : 'डेमो जांचें',
		'pt_BR' : 'Verificar demonstração',
		'fr_FR' : 'Vérifier la démo',
	},
	'We Are Coming Soon' : {
		'italian' : 'Stiamo arrivando presto',
		'jp_JP' : '近日公開予定',
		'ar_TN' : 'نحن قادمون قريبا',
		'tr_TR' : 'Yakında geliyoruz',
		'de_DE' : 'Wir kommen bald',
		'hi_IN' : 'हम जल्द ही आ रहे हैं',
		'pt_BR' : 'nós estamos chegando em breve',
		'fr_FR' : 'nous arrivons bientôt',
	},
	'Coming Soon' : {
		'italian' : 'Prossimamente',
		'jp_JP' : '近日公開',
		'ar_TN' : 'قريبا',
		'tr_TR' : 'Çok yakında',
		'de_DE' : 'Kommt bald',
		'hi_IN' : 'जल्द आ रहा है',
		'pt_BR' : 'Em breve',
		'fr_FR' : 'Bientôt disponible',
	},
	'Home' : {
		'italian' : 'Casa',
		'jp_JP' : 'ホーム',
		'ar_TN' : 'الصفحة الرئيسية',
		'tr_TR' : 'Ev',
		'de_DE' : 'Zuhause',
		'hi_IN' : 'घर',
		'pt_BR' : 'Casa',
		'fr_FR' : 'Accueil',
	},
	'About' : {
		'italian' : 'Di',
		'jp_JP' : '約',
		'ar_TN' : 'حول',
		'tr_TR' : 'hakkında',
		'de_DE' : 'Über',
		'hi_IN' : 'के बारे में',
		'pt_BR' : 'Sobre',
		'fr_FR' : 'Sur',
	},
	'Portfolio' : {
		'italian' : 'Portafoglio',
		'jp_JP' : 'ポートフォリオ',
		'ar_TN' : 'محفظة',
		'tr_TR' : 'Portföy',
		'de_DE' : 'Portfolio',
		'hi_IN' : 'पोर्टफोलियो',
		'pt_BR' : 'Portfólio',
		'fr_FR' : 'Portefeuille',
	},
	'Contact' : {
		'italian' : 'Contatto',
		'jp_JP' : '連絡先',
		'ar_TN' : 'اتصل',
		'tr_TR' : 'İletişim',
		'de_DE' : 'Kontakt',
		'hi_IN' : 'संपर्क करें',
		'pt_BR' : 'Contato',
		'fr_FR' : 'Contact',
	},
	'Food is Ready' : {
		'italian' : 'Il cibo è pronto',
		'jp_JP' : '食べ物は準備ができています',
		'ar_TN' : 'الطعام جاهز',
		'tr_TR' : 'Yemek hazır',
		'de_DE' : 'Das Essen ist fertig',
		'hi_IN' : 'खाना तैयार है',
		'pt_BR' : 'A comida está pronta',
		'fr_FR' : 'La nourriture est prête',
	},
	'We are launching soon please' : {
		'italian' : 'Ci lanceremo presto per favore',
		'jp_JP' : '近日発売予定です',
		'ar_TN' : 'نحن نطلق قريبا من فضلك',
		'tr_TR' : 'Yakında başlıyoruz lütfen',
		'de_DE' : 'Wir starten bald bitte',
		'hi_IN' : 'हम जल्द ही शुरू कर रहे हैं',
		'pt_BR' : 'Vamos lançar em breve, por favor',
		'fr_FR' : 'Nous lançons bientôt sil vous plaît',
	},
	'reload after minutes' : {
		'italian' : 'ricaricare dopo pochi minuti',
		'jp_JP' : '数分後にリロード',
		'ar_TN' : 'إعادة تحميل بعد دقائق',
		'tr_TR' : 'dakikalar sonra yeniden yükle',
		'de_DE' : 'nach Minuten neu laden',
		'hi_IN' : 'मिनटों के बाद पुनः लोड करें',
		'pt_BR' : 'recarregar após minutos',
		'fr_FR' : 'recharger après quelques minutes',
	},
	
	'placeholder::element:#SubscribeInput': {
		'italian' : 'Il tuo indirizzo di posta elettronica',
		'jp_JP' : 'メールアドレス',
		'ar_TN' : 'عنوان بريدك الإلكتروني',
		'tr_TR' : 'e',
		'de_DE' : 'deine Emailadresse',
		'hi_IN' : 'आपका ईमेल पता',
		'pt_BR' : 'Seu endereço de email',
		'fr_FR' : 'Votre adresse email',
	},
	
	'title::element:.gallery-media': {
		'italian' : 'Titolo Come Here',
		'jp_JP' : 'タイトルはここに来る',
		'ar_TN' : 'العنوان تعال هنا',
		'tr_TR' : 'Başlık Buraya Gel',
		'de_DE' : 'Titel Komm her',
		'hi_IN' : 'शीर्षक यहाँ आओ',
		'pt_BR' : 'Título Come Here',
		'fr_FR' : 'Titre Venez ici',
	}
	
};
	
var handleLanguageTranslation = function(){
	$('#selectLanguageDropdown').localizationTool({
		'defaultLanguage' : 'en_GB', /* (optional) although must be defined if you don't want en_GB */
		'showFlag': true,            /* (optional) show/hide the flag */
		'showCountry': true,         /* (optional) show/hide the country name */
		'showLanguage': true,        /* (optional) show/hide the country language */
		'languages' : languages,
		'strings' : translation_string
	});
}


jQuery(window).on("load", function (e) {
	
	//handleLanguageTranslation();
	
});